<!-- # Child Rmarkdown Document for scRNA Labeling QC outputs-->
<!-- Parent document must have a variable "rna_in_dir" containing a subfolder "labeled_h5" -->

```{r test, include = FALSE}
    rna_in_dir <- "/Users/lauren.okada/Packages/scrna-batch-report/inst/extdata/FullBatch"
   # rna_in_dir <- "/Users/lauren.okada/Packages/scrna-batch-report/inst/extdata/X002"
```

```{r scrna_label_dependency_check, include = FALSE}
assertthat::assert_that(exists("rna_in_dir"))
assertthat::assert_that(length(dir(file.path(rna_in_dir,"hash")))>0)
```  


#### Seurat Labeling Scores

```{r cell_labeling, fig.height = 8, fig.width = 20}
stm("Plotting Seurat labeling score distributions")

cell_type_palette <- batchreporter::seurat_3_cell_palette()

# quality scores by sample
meta_label <- meta[ ,.(median_quality = median(seurat_pbmc_type_score)), by = seurat_pbmc_type]
meta_label[, median_quality_label := sprintf("median = %.3f", round(median_quality,3))]

ggplot(meta, aes(seurat_pbmc_type_score, fill = seurat_pbmc_type)) +
  geom_histogram(bins = 30) +
  scale_color_discrete() +
  geom_text(data = meta_label, x = -Inf, y = Inf, hjust = -0.1, vjust = 1.5, size = 7, aes(label = median_quality_label))+
  ggtitle("Label Quality Score by Cell Label Type") +
  xlab("Label Score") +
  facet_wrap( ~ seurat_pbmc_type, ncol= 1) +
  scale_fill_manual(values = cell_type_palette$cell_color, labels = cell_type_palette$seurat3_pbmc_type) +
  theme_bw() +
  theme(title = element_text(size = 24),
        legend.text = element_text(size = 18),
        strip.text = element_text(size = 20, face = "bold"),
        axis.text = element_text(size = 14),
        axis.title = element_text(size = 20))+
  facet_wrap(~seurat_pbmc_type, scales = "free_y")

```

[Return to Top](#top_cell_labeling)

#### UMAP All Cells

Batch-level UMAP using `r {nPC}` principal components (`r {cumvar_string}`% explained variance) selected by jackstraw.

```{r umap_labels,  esults = "asis", fig.height = 18, fig.width = 20, class.output = "superbigimage"}
point_size <- 0.2

# Cell Types
g_base <- ggplot(umapDF, aes(UMAP_1_merged, UMAP_2_merged))

stm("Plotting cell type UMAP")
g1 <- g_base +
  geom_point(alpha = 1, size = point_size, aes(color = seurat_pbmc_type)) +
  ggtitle("Cell Labels")+
  scale_color_manual(values = cell_type_palette$cell_color,
                     breaks = cell_type_palette$seurat3_pbmc_type) +
  theme_bw() +
  theme(aspect.ratio = 1/1,
        title = element_text(size = 20),
        legend.key.size = unit(1, 'lines'),
        legend.text = element_text(size = 14)) +
  guides(colour = guide_legend(override.aes = list(size = 3)))

# Labeling Scores
stm("Plotting Labeling Score UMAP")
g2 <- g_base +
  geom_point(alpha = 1, size = point_size, aes(color = seurat_pbmc_type_score)) +
  ggtitle("Label Scores")+
  scale_color_gradientn(limits = c(0,1),colours = c("blue", "green3","yellow","red"),
                        breaks = c(0,0.25,0.5,0.75,1)) +
  theme_bw() +
  theme(aspect.ratio = 1/1,
        title = element_text(size = 20),
        legend.text = element_text(size = 14))

# Cell Cycle Scores
stm("Plotting Cell Cycle Score UMAP")
g3  <- ggplot(umapDF %>% dplyr::filter(Phase == "G1"), aes(UMAP_1_merged, UMAP_2_merged))  +
  geom_point(alpha = 0.3, size = point_size, color = "blue") +
  ggtitle("G1 Cells")+
  theme_bw() +
  theme(aspect.ratio = 1/1,
        title = element_text(size = 20),
        legend.text = element_text(size = 14))

stm("Plotting Cell Cycle Score UMAP")
g4  <- ggplot(umapDF %>% dplyr::filter(Phase == "S"), aes(UMAP_1_merged, UMAP_2_merged))  +
  geom_point(alpha = 0.3, size = point_size, color = "forestgreen") +
  ggtitle("S Cells")+
  theme_bw() +
  theme(aspect.ratio = 1/1,
        title = element_text(size = 20),
        legend.text = element_text(size = 14))
stm("Plotting Cell Cycle Score UMAP")
g5  <- ggplot(umapDF %>% dplyr::filter(Phase == "G2M"), aes(UMAP_1_merged, UMAP_2_merged))  +
  geom_point(alpha = 0.3, size = point_size, color = "orange") +
  ggtitle("G2M Cells")+
  theme_bw() +
  theme(aspect.ratio = 1/1,
        title = element_text(size = 20),
        legend.text = element_text(size = 14))


aligned_plots <- cowplot::align_plots(g1, g2, g3, g4, g5, align = "hv", axis = "tblr")  # uniform plot sizing

cowplot::plot_grid(aligned_plots[[1]],
                   aligned_plots[[2]],
                   aligned_plots[[3]],
                   aligned_plots[[4]],
                   aligned_plots[[5]],
                   ncol = 2)

```

[Return to Top](#top_cell_labeling)


#### UMAP by Fraction Mitochondrial UMI

```{r }

```

```{r cell_labeling_lowmito, fig.height = 20, fig.width = 20}
stm("Plotting Batch UMAP labeling, by fraction mitochondrial reads")
g1_mito <- g1 +
  facet_grid(~fct_mito_umi_binary) +
  ggtitle("Cell Labels by Fraction Mitochondrial UMI")+
  theme(strip.text = element_text(size = 18))

# Labeling Scores
stm("Plotting Batch UMAP labeling scores, by fraction mitochondrial reads")
g2_mito <- g2 +
  facet_grid(~fct_mito_umi_binary) +
  ggtitle("Cell Label Scores by Fraction Mitochondrial UMI")+
  theme(strip.text = element_text(size = 18))

aligned_plots <- cowplot::align_plots(g1_mito, g2_mito, align = "hv", axis = "tblr")  # uniform plot sizing

cowplot::plot_grid(aligned_plots[[1]],
                   aligned_plots[[2]],
                   ncol = 1)

```

[Return to Top](#top_cell_labeling)

#### Cell Types by Fraction Mitochondrial Read Group
```{r cell_labeling_mito_celltypes, fig.height = 10, fig.width = 20}
stm("Plotting Batch UMAP labeling scores, by fraction mitochondrial reads")
# summaryScores <- umapDF %>%
#   group_by()

label_scores_mito <- function(umapDF, mito_binary = "fct_mito_umi_binary"){
  summary_all <- umapDF %>%
    group_by(seurat_pbmc_type) %>%
    summarize(N = n(), .groups = "drop") %>%
    ungroup() %>%
    mutate(pct = N/sum(N)) %>%
    mutate(group = "All")

  label_order <- names(sort(table(summary_all$seurat_pbmc_type), decreasing = TRUE))

  summary_split <- umapDF %>%
    group_by(seurat_pbmc_type, !!rlang::parse_expr(mito_binary)) %>%
    summarize(N = n(), .groups = "drop") %>%
    ungroup() %>%
    group_by(!!rlang::parse_expr(mito_binary)) %>%
    mutate(pct = N/sum(N)*100 ) %>%
    rename(group = !!mito_binary) %>%
    mutate(group = paste0("FractionMT",group))

  summary_merge <- rbind(summary_all, summary_split) %>%
    mutate(seurat_pbmc_type = factor(seurat_pbmc_type, levels = label_order))

  ggplot(summary_merge, aes(factor(seurat_pbmc_type, levels = label_order), pct, fill = group))+
    geom_bar(stat = "identity", position = "dodge") +
    xlab("Cell Type Label") +
    ylab("Percent Cell Type within Group") +
    theme(text = element_text(size = 24))
}

label_scores_mito(umapDF)

```

#### Marker Visualization

```{r marker_umap,fig.height = 35, fig.width = 25,  class = "superbigimage"}
stm("Plotting UMAP of marker genes")
genes <- c("CD3D","CD3E", "CD3G","CD247","CD4", "CD8A",
            "HLA-DRA", "CD14", "FCGR3A", "IL3RA", "ITGAX",
           "CD19", "MS4A1", "CD79A", "NCAM1", "NKG7", "PPBP", "IL7R",
           "FUT4", "ITGAM","FCGR2B","FCER1A")
cDF <- normCounts
# rownames(cDF) <- featDF$name[featDF$id == rownames(cDF)]

# Add normalized gene counts to the analysis dataframe (UMAP + meta)
markerDF <- t(cDF[genes, ]) %>% as.data.frame()
umapDF2 <- umapDF[, c("UMAP_1_merged", "UMAP_2_merged","fct_mito_umi")]
# table(rownames(markerDF) == rownames(umapDF2))
umapDF2 <- cbind(umapDF2, markerDF) %>%
  tidyr::gather(key = gene, value = value, -UMAP_1_merged, -UMAP_2_merged)
umapDF2$gene <- factor(umapDF2$gene, levels = genes)

# plot UMAP per marker
marker_umap_l <- list()
for(G in genes) {
  umapDF3 <- umapDF2 %>% dplyr::filter(gene %in% G)
  marker_umap_l[[G]] <- ggplot(data = umapDF3,
                               mapping = aes(x = UMAP_1_merged,
                                             y = UMAP_2_merged,
                                             color = as.numeric(value))) +
    geom_point(size = 0.8) +
    scale_color_gradient(low = "white", high = "red") +
    labs(x = "UMAP 1", y = "UMAP 2") +
    labs(color = "NormCount") +
    ggtitle(G)+
    theme(aspect.ratio = 1/1,
          panel.background = element_rect(fill = "#b6b7b2"),
          plot.title = element_text(size = 20),
          axis.text.x = element_text(size = 12, color = "black"),
          axis.text.y = element_text(size = 12, color = "black"),
          axis.line = element_line(color = "grey"),
          panel.grid = element_blank())
}



cowplot::plot_grid(plotlist = marker_umap_l, ncol = 4)

```

[Return to Top](#top_cell_labeling)
